### ISSUE TITLE
Download pdf and scrape

### ISSUE THREAD

**Issue by nyandika** [DanNduati/Stima-Parser#3]
Would it be possible instead of providing the pdf to have the library do the download and then scrape it?
or is that out of scope

**Comment by DanNduati** [comment]
Hello @nyandika  you don't provide the pdf you provide a path to store the pdfs after they get scraped.

**Comment by DanNduati** [comment]
If you mean extracting data off the documents I figured i should separate the two so I have a separate package that does that check it out [here](https://github.com/DanNduati/Stima_parser)

**Comment by nyandika** [comment]
Ah yes, that makes sense.
Closing this
